---
version: 3
images:
  base_image:
    name: quay.io/ansible/awx-ee:latest

dependencies:
  system: bindep.txt
  python: requirements.txt

additional_build_steps:
  prepend_base:
    - RUN yum -y update && yum install -y ftp
  append_base:
    - ENV timmay_prod_version=v1.4
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 0
    - RUN curl -o /runner/ansible.cfg https://raw.githubusercontent.com/timmayg/timmay-prod/main/ansible.cfg
    - RUN curl -o /runner/release-notes.json https://raw.githubusercontent.com/timmayg/timmay-prod/main/release-notes.json
    - ENV ANSIBLE_CONFIG=/runner/ansible.cfg
    - RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/microsoft.repo
    - RUN yum install -y powershell
